### ISSUE TITLE
Is it possible to edit the name of a thought once it is created? 

### ISSUE THREAD

**Issue by brodonn** [n3xah/issues#10]
I named my category "Books I should read" but now I think I want to rename it books with two sections of want to read and read and maybe currently reading but I can't figure out how to rename my thought.

**Comment by veronicamarie24** [comment]
@brodonn any thought can be edited by clicking on the text, and it will allow you to then type into the input field :)


https://github.com/user-attachments/assets/7bbcbac7-8e49-4c07-ad97-36f52a8eb194

**Comment by veronicamarie24** [comment]
Let me know if this didn't work out for you or if you have any other thoughts pertaining to the intuitiveness of editing thoughts :thumbsup:
