### ISSUE TITLE
Thought suggestions seem to not be processed

### ISSUE THREAD

**Issue by kec056** [n3xah/issues#2]
It seems like when the chat history gets long enough or the number of thoughts get high enough, asking n3xa to add/edit/delete thoughts starts to get inconsistent. Example below to try to remove the duplicate "Day 3: London Sightseeing (Day 2)" thoughts.

![Action on thoughts not being processed](https://github.com/n3xah/issues/assets/12588367/6dba61d1-ec80-4f2d-ab56-ee934a857552)

**Comment by veronicamarie24** [comment]
@kec056 I deployed some updates that might fix this, let me know if you're still experiencing this and I can take a look at the logs at the time that you test it to see what else is happening
